version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - Abdulwahaab710
  labels:
  - dependencies
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
