AllCops:
  Exclude:
    - config/unicorn.rb
    - config/routes.rb
    - db/**
    - Guardfile
    - bin/**
Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
