version: "3"

volumes:
  db-data:
    external: false
  redis-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    image: postgres:9.5
    volumes:
      - db-data:/user/local/pgsql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis-data:/data

  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  cable:
    depends_on:
      - redis
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - "28080:28080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  nginx:
    image: nginx
    links:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4000:80"
