version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    image: postgres:9.5
    volumes:
      - db-data:/user/local/pgsql/data

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db

